### ISSUE TITLE
[SPP]Problème avec l'URL de staging

### ISSUE THREAD

**Issue by A905062** [etalab-ia/albert-spp#2]
Bonjour,

Nous avons un problème avec les appels API Albert sur l'environnement de staging correspondant à l'URL suivante :
https://albert.staging.etalab.gouv.fr/api/spp/docs

Apparemment, cette URL n'existe plus, pourriez vous s'il vous plait nous donner la nouvelle URL de l'instance de staging ?

Merci d'avance !

**Comment by leoguillaume** [comment]
Bonjour, l'URL de staging est https://spp.staging.etalab.gouv.fr
Nous avions transmis le changement d'URL par mail et David m'avait fait par du changement de votre côté le 5 juin dernier.

**Comment by A905062** [comment]
Merci beaucoup Leo pour cette réponse claire et rapide.

Le problème est réglé de notre côté.

Désolé du dérangement.
